from pydantic import BaseModel, ConfigDict, Field, EmailStr
from datetime import datetime


class UserBase(BaseModel):
    username : str = Field(min_length=1, max_length=50)
    email : EmailStr = Field(max_length=120)
    
class UserCreate(UserBase):
    ...
    
class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)
    
    id : int
    image_file : str | None
    image_path : str
    
class UserUpdate(BaseModel):
    username: str | None = Field(default=None, min_length=1, max_length=50)
    email: EmailStr | None = Field(default=None, max_length=120)
    image_file: str | None = Field(default=None, min_length=1, max_length=200)


# this is kind of a serializer schema which is used by pydantic to validate data in runtime & it uses type hints
class PostBase(BaseModel):
    title: str = Field(min_length=1, max_length=100)
    content : str = Field(min_length=1)
    
    
class PostCreate(PostBase):
    user_id : int

class PostResponse(PostBase):
    model_config = ConfigDict(from_attributes=True)
    # fields generated by backend
    id : int
    user_id : int
    date_posted : datetime
    author : UserResponse # add nested user data in result json

class PostUpdate(PostBase):
    title: str | None = Field(default=None, min_length=1, max_length=100)
    content : str | None = Field(default=None, min_length=1)