from pydantic import BaseModel, ConfigDict, Field


# this is kind of a serializer schema which is used by pydantic to validate data in runtime & it uses type hints
class ProductBase(BaseModel):
    name: str = Field(min_length=1, max_length=200)
    price : float = Field(ge=1)
    is_sale : bool | None = None
    
    
class ProductCreate(ProductBase):
    pass

class ProductResponse(ProductBase):
    model_config = ConfigDict(from_attributes=True)
    # fields generated by backend
    id : int
    date_posted : str
